api/urls.py
from rest_framework import routers
from .views import *


router = routers.DefaultRouter()
router.register('brands', MarcaViewSet, 'brands')
router.register('years', AnnoViewSet, 'years')
router.register('models', ModeloViewSet, 'models')

urlpatterns = router.urls

frontend/apps/cotizador/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView as AuthLoginView, LogoutView
from django.contrib.auth.forms import AuthenticationForm
from captcha.fields import CaptchaField


class LoginForm(AuthenticationForm):
    captcha = CaptchaField()


class LoginView(AuthLoginView):
    authentication_form = LoginForm


app_name = 'cotizador'

urlpatterns = [
    path('', inicio, name='inicio'),
    path('cotizar', cotizar, name='cotizar'),
    path('perfil/', perfil, name='perfil'),
    path('change_password/', change_password, name='change_password'),
    path('siniestros', siniestros, name='siniestros'),
    path('recomendados/', recomendados, name='recomendados'),
    path('misseguros', misseguros, name='misseguros'),
    path('solicitar_baja', solicitar_baja, name='solicitar_baja'),
    path('solicitar_baja_auto', solicitar_baja_auto, name='solicitar_baja_auto'),
    path('solicitud_renovacion_auto', solicitud_renovacion_auto, name='solicitud_renovacion_auto'),
    path('contactanos/', contactanos, name='contactanos'),
    path('get_data/', get_data, name='get_data'),
    path('get_modelos/', get_modelos, name='get_modelos'),
    path('get_annos/', get_annos, name='get_annos'),
    path('cotizacion_manual/', cotizacion_manual, name='cotizacion_manual'),
    path('guardar_poliza/', guardar_poliza, name='guardar_poliza'),
    path('generar_cotizacion/', generar_cotizacion, name='generar_cotizacion'),
    path('calcular_tabla_pagos/', calcular_tabla_pagos_polizas, name='calcular_tabla_pagos'),
    path('print_recibo/', print_recibo, name='print_recibo'),
    path('print_cotizacion/', print_cotizacion, name='print_cotizacion'),
    path('print_documentos/', print_documentos, name='print_documentos'),
    path('print_condiciones/', print_condiciones, name='print_condiciones'),
    path('print_orden_trabajo/', print_orden_trabajo, name='print_orden_trabajo'),
    path('print_orden_trabajo_sepelio/', print_orden_trabajo_sepelio, name='print_orden_trabajo_sepelio'),
    path('print_orden_trabajo_accidente/', print_orden_trabajo_accidente, name='print_orden_trabajo_accidente'),
    path('print_cesion/', print_cesion, name='print_cesion'),
    path('print_soa/', print_soa, name='print_soa'),
    path('enviar_contacto/', enviar_contacto, name='enviar_contacto'),
    path('admin_tasks/', admin_tasks, name='admin_tasks'),


    path('guardar_sepelio/', guardar_sepelio, name='guardar_sepelio'),
    path('costo_accidente/', costo_accidente, name='costo_accidente'),
    path('guardar_accidente/', guardar_accidente, name='guardar_accidente'),
    path('restablecer_password/', restablecer_password, name='restablecer_password'),
    path('invitacion/', invitacion, name='invitacion'),

    path('download/', download, name="download"),
    path('login/', LoginView.as_view(template_name='cotizador/login.html'), name="login"),
    path('logout/', LogoutView.as_view(next_page="/"), name="logout"),

    path('ingresar_numero_poliza', ingresar_numero_poliza, name="ingresar_numero_poliza"),
    path('javascript/<file>/', javascript, name="javascript"),
]

frontend/apps/trustseguros/urls.py
from django.urls import path
from .views import *

app_name = "trustseguros"

urlpatterns = [
    path('', index, name="index"),
    path('profile/', profile, name="profile"),
    path('persona_natural/', PersonaNatural.as_view(), name="persona_natural"),
    path('persona_juridica/', PersonaJuridica.as_view(), name="persona_juridica"),
    path('lineas/', Lineas.as_view(), name="lineas"),
    path('campains/', Campains.as_view(), name="campains"),
    path('tipo_doc/', TiposDocumentos.as_view(), name="tipo_doc"),
    path('aseguradoras/', Aseguradoras.as_view(), name="aseguradoras"),
    path('tarifas/', Tarifas.as_view(), name="tarifas"),
    path('grupos/', Grupos.as_view(), name="grupos"),
    path('ramos/', Ramos.as_view(), name="ramos"),
    path('subramos/', SubRamos.as_view(), name="subramos"),
    path('seguimientos/', Seguimientos.as_view(), name="seguimientos"),
    path('polizas/', Polizas.as_view(), name="polizas"),
    path('tramites/', Tramites.as_view(), name="tramites"),
    path('configcotizador/', ConfiguracionCotizador.as_view(), name="configcotizador"),
    path('cargaoportunidades/', CargaOportunidades.as_view(), name="cargaoportunidades"),
    path('usuarios/', Usuarios.as_view(), name="usuarios"),
    path('oportunidades/<int:linea>/', Oportunidades.as_view(), name="oportunidades"),
    path('roles/', Roles.as_view(), name="roles"),
    path('documentos/', documentos, name="documentos"),
    path('comentarios/', comentarios, name="comentarios"),
    path('cobranza/', Recibos.as_view(), name="recibos"),
    path('siniestrotramite/', SiniestroTramite.as_view(), name="siniestrotramite"),
    path('siniestro/', Siniestros.as_view(), name="siniestro"),
    path('travel_currencies/', CurrencyTravelView.as_view(), name="travel_currencies"),
    path('travel_categories/', PlanCategoryTravelView.as_view(), name="travel_categories"),
    path('travel_territories/', TerritoryTravelView.as_view(), name="travel_territories"),
    path('travel_countries/', CountryTravelView.as_view(), name="travel_countries"),
    path('travel_cities/', CityTravelView.as_view(), name="travel_cities"),
    path('travel_plans/', PlanTravelView.as_view(), name="travel_plans"),
    path('travel_asistencias/', AsistenciaTravelView.as_view(), name="travel_asistencias"),



    path('reporte_tramite/', ReporteTramite.as_view(), name="reporte_tramite"),
    path('reporte_poliza_emitida/', ReportePolizaEmitida.as_view(), name="reporte_poliza_emitida"),
    path('reporte_poliza_cancelada/', ReportePolizaCancelada.as_view(), name="reporte_poliza_cancelada"),
    path('reporte_poliza_renovada/', ReportePolizaRenovada.as_view(), name="reporte_poliza_renovada"),
    path('reporte_poliza_vencer/', ReportePolizaPorVencer.as_view(), name="reporte_poliza_vencer"),
    path('reporte_crm/', ReporteCRM.as_view(), name="reporte_crm"),
    path('reporte_cotizaciones/', ReporteCotizaciones.as_view(), name="reporte_cotizaciones"),
    path('reporte_siniestro/', ReporteSiniestro.as_view(), name="reporte_siniestro"),
    path('reporte_mora/', ReporteMora.as_view(), name="reporte_mora"),
    path('reporte_comision/', ReporteComision.as_view(), name="reporte_comision"),
]

webtrust/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('backend/', include('backend.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/ajax/', include('grappelli_extras.ajax_urls')),
    path('cotizador/', include('frontend.apps.cotizador.urls')),
    path('trustseguros/', include('frontend.apps.trustseguros.urls')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/forms.py
from django import forms
from .models import *


class AseguradoraField(forms.ModelChoiceField):

    def __init__(self, queryset=Aseguradora.objects.all(), *, empty_label="---------",
                 required=True, widget=None, label=None, initial=None,
                 help_text='', to_field_name=None, limit_choices_to=None,
                 **kwargs):
        super(AseguradoraField, self).__init__(queryset, empty_label="---------",
                                               required=True, widget=None, label=None, initial=None,
                                               help_text='', to_field_name=None, limit_choices_to=None,
                                               **kwargs)


class RamoField(forms.ModelChoiceField):

    def __init__(self, queryset=Ramo.objects.all(), *, empty_label="---------",
                 required=True, widget=None, label=None, initial=None,
                 help_text='', to_field_name=None, limit_choices_to=None,
                 **kwargs):
        super(RamoField, self).__init__(queryset, empty_label="---------",
                                        required=True, widget=None, label=None, initial=None,
                                        help_text='', to_field_name=None, limit_choices_to=None,
                                        **kwargs)


class SubRamoField(forms.ModelChoiceField):

    def __init__(self, queryset=SubRamo.objects.all(), *, empty_label="---------",
                 required=True, widget=None, label=None, initial=None,
                 help_text='', to_field_name=None, limit_choices_to=None,
                 **kwargs):
        super(SubRamoField, self).__init__(queryset, empty_label="---------",
                                           required=True, widget=None, label=None, initial=None,
                                           help_text='', to_field_name=None, limit_choices_to=None,
                                           **kwargs)


class ClienteField(forms.ModelChoiceField):

    def __init__(self, queryset=Cliente.objects.all(), *, empty_label="---------",
                 required=True, widget=None, label=None, initial=None,
                 help_text='', to_field_name=None, limit_choices_to=None,
                 **kwargs):
        super(ClienteField, self).__init__(queryset, empty_label="---------",
                                           required=True, widget=None, label=None, initial=None,
                                           help_text='', to_field_name=None, limit_choices_to=None,
                                           **kwargs)


class ProfileForm(forms.ModelForm):
    email = forms.EmailField(label="email", required=False)

    class Meta:
        model = Cliente
        fields = '__all__'


class ProspectoForm(forms.ModelForm):
    class Meta:
        model = ClienteProspecto
        fields = '__all__'


def _marcas():
    return [(m, m) for m in Referencia.objects.distinct('marca').values_list('marca', flat=True)]


class MarcaRecargoForm(forms.ModelForm):
    marca = forms.ChoiceField(choices=_marcas)

    class Meta:
        model = Marca
        fields = '__all__'


class InvitationForm(forms.Form):
    html = forms.CharField(widget=forms.Textarea)


class SoportesWidget(forms.Widget):
    template_name = 'backend/widgets/soportes.html'

    def format_value(self, value):
        if value:
            content_type = ContentType.objects.get(app_label=value._meta.app_label,
                                                   model=value._meta.model_name)
            return {
                'type': content_type,
                'pk': value.pk,
            }
        return {}


class PolizaForm(forms.ModelForm):
    media = forms.Field(label="Soportes", required=False,
                        widget=SoportesWidget())

    class Meta:
        model = Poliza
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        instance = kwargs.get('instance', None)
        if instance:
            kwargs.update(initial={
                'media': instance
            })
        super(PolizaForm, self).__init__(*args, **kwargs)

frontend/apps/cotizador/forms.py
from backend.models import Recomendado
from django import forms
from django.core.validators import RegexValidator


class RecomendadoForm(forms.ModelForm):
    primer_nombre = forms.CharField(max_length=125)
    apellido_paterno = forms.CharField(max_length=125)
    celular = forms.CharField(max_length=8, validators=[RegexValidator('[0-9]{8,8}'), ])

    class Meta:
        model = Recomendado
        fields = '__all__'

frontend/templates/trustseguros/lte/includes/nuevo-pago.html
{% load datatables %}
<tr>
    <td>
        <input type="hidden" name="{{ form.prefix }}"
               value="{% if form.instance.id %}{{ form.instance.id|stringformat:'i' }}{% endif %}">
        {{ form.fecha_pago|as_inline_field }}
    </td>
    <td>
        {{ form.monto|as_inline_field }}
    </td>
    <td>
        {{ form.referencia_pago|as_inline_field }}
    </td>
    <td>
        {{ form.medio_pago|as_inline_field }}
    </td>
    <td>
        {{ form.fecha_pago_comision|as_inline_field }}
    </td>
    <td>
        {{ form.comision|as_inline_field }}
    </td>
    <td>
        {% ifnotequal form.instance.cuota.estado 3 %}
            <button type="button" class="btn btn-danger btn-del-pago"
                    {% if form.instance.id %}data-id="{{ form.instance.id|stringformat:'i' }}"{% endif %}>
                <i class="fa fa-trash"></i>
            </button>
        {% endifnotequal %}
    </td>
</tr>

frontend/templates/trustseguros/lte/includes/nuveo-pago.html
{% load datatables %}
<tr>
    <td>
        <input type="hidden" name="{{ form.prefix }}"
               value="{% if form.instance.id %}{{ form.instance.id }}{% endif %}">
        {{ form.monto|as_inline_field }}
    </td>
    <td>
        {{ form.referencia_pago|as_inline_field }}
    </td>
    <td>
        {{ form.medio_pago|as_inline_field }}
    </td>
    <td>
        {{ form.fecha_pago|as_inline_field }}
    </td>
    <td>
        <button type="button" class="btn btn-danger btn-del-pago">
            <i class="fa fa-trash"></i>
        </button>
    </td>
</tr>

frontend/templates/trustseguros/lte/includes/ofertas.html
{% load humanize %}

<form action="." id="form-register" method="post">
    <input type="hidden" name="oportunity" value="{{ oportunity.id }}">
    {% if poliza %}
        <div class="row">
            <div class="col">La póliza # {{ poliza.no_poliza }} existe! y se encuentra en estado:
                {{ poliza.get_estado_poliza_display }}. Vigencia de: {{ poliza.fecha_emision|date:'d/m/Y' }} hasta
                {{ poliza.fecha_vence|date:'d/m/Y' }}
            </div>
        </div>
    {% endif %}
    {% if oportunity.cotizado %}
        <table class="table">
            <thead>
            <tr>
                <th></th>
                <th>Aseguradora</th>
                <th>Prima total</th>
            </tr>
            </thead>

            <tbody>
            {% for oferta in oportunity.ofertas_cotizacion %}
                <tr>
                    <td style="text-align: center; vertical-align: middle">
                        <input type="radio" name="aseguradora" value="{{ oferta.aseguradora.id }}" required="required">
                    </td>
                    <td>
                        <img src="{{ oferta.aseguradora.logo.url }}" style="max-width: 85px">
                    </td>
                    <td>U$ {{ oferta.prima_total|intcomma }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <table class="table">
            <thead>
            <tr>
                <th>Aseguradora</th>
                <th>Prima total</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    <select name="aseguradora" id="id_aseguradora" class="form-control">
                        {% for aseguradora in aseguradoras %}
                            <option value="{{ aseguradora.id }}">{{ aseguradora.name }}</option>
                        {% endfor %}
                    </select>
                </td>
                <td>
                    <input type="number" placeholder="PRIMA"
                           step=".01"
                           class="form-control" name="prima" id="id_prima" required>
                </td>
            </tr>
            </tbody>
        </table>
    {% endif %}
    <button type="submit" class="btn btn-primary btn-trust">
        <i class="fa fa-file-archive"></i>
        <span>Registrar</span>
    </button>
</form>

frontend/templates/trustseguros/lte/includes/send-email-template-2.html
{% load static humanize mathfilters %}
<form action="." method="post" enctype="multipart/form-data" id="send-mail-form">
    {% csrf_token %}

    <input type="hidden" name="oportunity_id" value="{{ oportunity.id }}">

    <table style="width: 100%">
        <tr>
            <td>
                <span class="send-mail-label">De:</span>
                <input class="send-mail-input" type="text" value="{{ oportunity.vendedor.email }}" name="de">
            </td>
        </tr>
        <tr>
            <td>
                <span class="send-mail-label">Para:</span>
                <input class="send-mail-input" type="text" value="{{ oportunity.prospect.email_personal }}" name="para">
            </td>
        </tr>
        <tr>
            <td><span class="send-mail-label">Asunto:</span>
                <input class="send-mail-input" type="text"
                       value="Oferta de seguro {{ oportunity.prospect.full_name }}" name="asunto">
            </td>
        </tr>
    </table>

    <textarea id="id_html" name="email_content" data-autosave="editor-content"
              autofocus>
    <div>
        <p>Buenos días</p>

        <p> Sr(a) {{ oportunity.prospect.full_name }}, permítanos presentarle una cotización de seguro para su vehículo con las mejores condiciones del mercado. Para esta cotización hemos buscado alternativas en compañías de seguros con prestigio Nacional.</p>



        <table style="margin-top: 10mm; border-collapse: collapse">
        <thead>
{#        <tr>#}
{#            <th colspan="{{ oportunity.ofertas_columns }}" class=""#}
{#                style="background-color: #51972d">#}
{#                Comparativo de sumas aseguradas, coaseguros y primas#}
{#            </th>#}
{#        </tr>#}
        <tr>
            <th style="border: 1px solid darkgreen; padding: 4px 0 0 0; text-align: center"><b>Compañia</b></th>
            {% for oferta in oportunity.ofertas.all %}
                <th style="border: 1px solid darkgreen; padding: 4px 0 15px 15px; text-align: center">
                    <img src="https://www.trustcorreduria.com{{ oferta.aseguradora.logo.url }}" width="65">
                </th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>

        <tr>
            <td style="border: 1px solid darkgreen; padding: 4px 0 15px 15px; text-align: center"><b>Suma asegurada</b>
            </td>
            {% for oferta in oportunity.ofertas_cotizacion %}
                <td style="border: 1px solid darkgreen; padding: 4px 0 0 0; text-align: center">
                    U$ {{ oferta.suma_asegurada|intcomma }}</td>
            {% endfor %}
        </tr>
        <tr>
            <td style="border: 1px solid darkgreen; padding: 4px 0 0 0; text-align: center"><b>Deducible</b></td>
            {% for oferta in oportunity.ofertas_cotizacion %}
                <td style="border: 1px solid darkgreen; padding: 4px 0 15px 15px; text-align: center">
                    U$ {{ oferta.deducible|intcomma }}</td>
            {% endfor %}
        </tr>
        <tr>
            <td style="border: 1px solid darkgreen; padding: 4px 0 15px 15px; text-align: center"><b>Coaseguro robo</b>
            </td>
            {% for oferta in oportunity.ofertas.all %}
                <td style="border: 1px solid darkgreen; padding: 4px 0 0 0; text-align: center">{{ oferta.coaseguro_robo }}
                    %
                </td>
            {% endfor %}
        </tr>
        <tr>
            <td style="border: 1px solid darkgreen; padding: 4px 0 15px 15px; text-align: center"><b>Coaseguro daños</b></td>
            {% for oferta in oportunity.ofertas_cotizacion %}
                <td style="border: 1px solid darkgreen; padding: 4px 0 0 0; text-align: center">{{ oferta.coaseguro_dano }}
                    %
                </td>
            {% endfor %}
        </tr>
        <tr>
            <td style="border: 1px solid darkgreen; padding: 4px 0 15px 15px; text-align: center"><b>Prima total</b></td>
            {% for oferta in oportunity.ofertas_cotizacion %}
                <td style="border: 1px solid darkgreen; padding: 4px 0 0 0; text-align: center">
                    U$ {{ oferta.total|intcomma }}</td>
            {% endfor %}
        </tr>
        </tbody>
    </table>

        <p>Favor indicarnos a qué dirección le podemos hacer llegar el carnet y póliza renovada; también solicito de
            su amable colaboración con el envío del soporte de cancelación de crédito a fin de invalidar las cesiones
            de derechos y realizar el cambio de contratante; en este sentido, adjunto carta de cambio de
            intermediario, para realizar dicho cambio de contratante.
            </p>

    </div>
        <br>
        <p>Atentamente</p>
        <p style="margin: 0">
            <b>
                <span style="color: rgb(47, 85, 151);">{{ oportunity.vendedor.get_full_name }}&nbsp;</span>
            </b>
            <br>
            <b>
                <span style="color: rgb(47, 85, 151);">Trust Correduría de Seguros SA</span>
            </b>
            <br>
            <b>
                <span style="color: rgb(56, 87, 35);">Teléfono: +505 2251-0108</span>
            </b>
            <br>
            <b>
                <span style="color: rgb(56, 87, 35);">Celular: {{ oportunity.vendedor.profile.celular }}</span>
            </b>
            <br>
            <b>
                <span style="color: rgb(56, 87, 35);">
                    <a
                        href="mailto:{{ oportunity.vendedor.email }}"
                        target="_blank">{{ oportunity.vendedor.email }}</a>
                </span>
            </b>
            <br>
            <b>
                <span style="color: rgb(56, 87, 35);"><a href="http://www.trustcorreduria.com/"
                                                         target="_blank">www.trustcorreduria.com</a></span>
            </b>
        </p>
    </textarea>

    <div class="send-email-attachment">
        <figure class="email-attachment">
            <img src="{% static 'trustseguros/lte/img/PDF_file_icon.png' %}">
            <figcaption>Cotización</figcaption>
        </figure>
    </div>

    <div class="send-email-buttons" style="display: flex; justify-content: flex-end">
        <button type="submit" class="btn btn-primary btn-trust">
            <i class="fa fa-paper-plane"></i>
            <span>Enviar</span>
        </button>
    </div>

</form>

frontend/templates/trustseguros/lte/includes/send-email-template.html
{% load static humanize %}
<form action="." method="post" enctype="multipart/form-data" id="send-mail-form">
    {% csrf_token %}

    <input type="hidden" name="oportunity_id" value="{{ oportunity.id }}">

    <table style="width: 100%">
        <tr>
            <td>
                <span class="send-mail-label">De:</span>
                <input class="send-mail-input" type="text" value="{{ oportunity.vendedor.email }}" name="de">
            </td>
        </tr>
        <tr>
            <td>
                <span class="send-mail-label">Para:</span>
                <input class="send-mail-input" type="text" value="{{ oportunity.prospect.email_personal }}" name="para">
            </td>
        </tr>
        <tr>
            <td><span class="send-mail-label">Asunto:</span>
                <input class="send-mail-input" type="text"
                       value="Oferta de seguro {{ oportunity.prospect.full_name }}" name="asunto">
            </td>
        </tr>
    </table>

    <textarea id="id_html" name="email_content" data-autosave="editor-content"
              autofocus>
    <div>
        <p>Buenos días</p>

        <p> Sr(a) {{ oportunity.prospect.full_name }}, permítanos presentarle una cotización de seguro para su vehículo con las mejores condiciones del mercado. Para esta cotización hemos buscado alternativas en compañías de seguros con prestigio Nacional.</p>


        <p>A continuación las opciones de seguro:</p>

        <table style="margin-top: 10mm; border-collapse: collapse">
        <thead>
        <tr>
            <th style="border: 1px solid darkgreen; padding: 4px 0 0 0; text-align: center"><b>Compañia</b></th>
        {% for oferta in oportunity.ofertas_cotizacion %}
            <th style="border: 1px solid darkgreen; padding: 4px 0 15px 15px; text-align: center">
            <img src="https://www.trustcorreduria.com{{ oferta.aseguradora.logo.url }}" width="65">
            </th>
        {% endfor %}
        </tr>
        </thead>
        <tbody>

        <tr>
            <td style="border: 1px solid darkgreen; padding: 4px 0 15px 15px; text-align: center"><b>Suma asegurada</b>
            </td>
        {% for oferta in oportunity.ofertas_cotizacion %}
            <td style="border: 1px solid darkgreen; padding: 4px 0 0 0; text-align: center">
            U$ {{ oferta.suma_asegurada|intcomma }}</td>
        {% endfor %}
        </tr>
        <tr>
            <td style="border: 1px solid darkgreen; padding: 4px 0 0 0; text-align: center"><b>Deducible</b></td>
        {% for oferta in oportunity.ofertas_cotizacion %}
            <td style="border: 1px solid darkgreen; padding: 4px 0 15px 15px; text-align: center">
            U$ {{ oferta.deducible|intcomma }}</td>
        {% endfor %}
        </tr>
        <tr>
            <td style="border: 1px solid darkgreen; padding: 4px 0 15px 15px; text-align: center"><b>Coaseguro robo</b>
            </td>
        {% for oferta in oportunity.ofertas_cotizacion %}
            <td style="border: 1px solid darkgreen; padding: 4px 0 0 0; text-align: center">{{ oferta.coaseguro_robo }}
            %
            </td>
        {% endfor %}
        </tr>
        <tr>
            <td style="border: 1px solid darkgreen; padding: 4px 0 15px 15px; text-align: center"><b>Coaseguro daños</b></td>
        {% for oferta in oportunity.ofertas_cotizacion %}
            <td style="border: 1px solid darkgreen; padding: 4px 0 0 0; text-align: center">{{ oferta.coaseguro_dano }}
            %
            </td>
        {% endfor %}
        </tr>
        <tr>
            <td style="border: 1px solid darkgreen; padding: 4px 0 15px 15px; text-align: center"><b>Prima total</b></td>
        {% for oferta in oportunity.ofertas_cotizacion %}
            <td style="border: 1px solid darkgreen; padding: 4px 0 0 0; text-align: center">
            U$ {{ oferta.total|intcomma }}</td>
        {% endfor %}
        </tr>
        </tbody>
    </table>

        <p>Los requisitos para tomar la póliza son:</p>

        <ul>
    <li>Copia de cédula</li>

    <li>Copia de circulación</li>

    <li>Inspección del vehículo</li>
    </ul>
        <p>Adjunto encontrará una cotización formal.</p>
        <p>En caso que usted prefiera trabajar con otra compañía, nos lo hace saber para presentarle oferta con las mejores condiciones del mercado.</p>

        <p>Agradeciendo nuevamente su confianza en nosotros, me despido en espera de su aprobación.</p>
        <p>Saludos cordiales.</p>
    </div>
        <br>
        <p>Atentamente</p>
        <p style="margin: 0">
            <span
                    style="color: rgb(136, 136, 136);"><b><span
                    style="color: rgb(47, 85, 151);">{{ oportunity.vendedor.get_full_name }}&nbsp;</span></b></span>
            <br><font color="#2f5597">Seguros de consumo<br></font>
        </p>
        <p style="margin: 0">
            <b>
                <span style="color: rgb(56, 87, 35);">Trust Correduría de Seguros SA</span>
            </b>
            <br>
            <b>
                <span style="color: rgb(56, 87, 35);">Teléfono: +505 2251-0108</span>
            </b>
            <br>
            <b>
                <span style="color: rgb(56, 87, 35);">Celular: {{ oportunity.vendedor.profile.celular }}</span>
            </b>
            <br>
            <b>
                <span style="color: rgb(56, 87, 35);">
                    Email:&nbsp;<a
                        href="mailto:{{ oportunity.vendedor.email }}"
                        target="_blank">{{ oportunity.vendedor.email }}</a>
                </span>
            </b>
            <br>
            <b>
                <span style="color: rgb(56, 87, 35);"><a href="http://www.trustcorreduria.com/"
              target="_blank">www.trustcorreduria.com</a></span>
            </b>
        </p>
    </textarea>

    <div class="send-email-attachment">
        <input id="id_attachment" type="file" name="adjuntos" multiple class="send-email-attachment-input">
        <div class="send-email-attachment-item">
            <figure class="email-attachment">
                <img src="{% static 'trustseguros/lte/img/PDF_file_icon.png' %}">
                <figcaption>Cotización</figcaption>
            </figure>
        </div>
    </div>

    <div class="send-email-buttons" style="display: flex; justify-content: flex-end">
        <button type="submit" class="btn btn-primary btn-trust">
            <i class="fa fa-paper-plane"></i>
            <span>Enviar</span>
        </button>
    </div>

</form>

frontend/templates/trustseguros/lte/includes/travel-confirmation-message.html
<div>
    <p>Plan: {{ plan.title }}</p>
    <p>desde {{ fecha_salida }} hasta {{ fecha_regreso }}</p>
    <p><b>{{ dias }} dias</b></p>
    <p><b>Total: U$ {{ total_orden }}</b></p>
</div>