api/urls.py
from rest_framework import routers
from .views import *


router = routers.DefaultRouter()
router.register('brands', MarcaViewSet, 'brands')
router.register('years', AnnoViewSet, 'years')
router.register('models', ModeloViewSet, 'models')

urlpatterns = router.urls

frontend/apps/cotizador/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView as AuthLoginView, LogoutView
from django.contrib.auth.forms import AuthenticationForm
from captcha.fields import CaptchaField


class LoginForm(AuthenticationForm):
    captcha = CaptchaField()


class LoginView(AuthLoginView):
    authentication_form = LoginForm


app_name = 'cotizador'

urlpatterns = [
    path('', inicio, name='inicio'),
    path('cotizar', cotizar, name='cotizar'),
    path('perfil/', perfil, name='perfil'),
    path('change_password/', change_password, name='change_password'),
    path('siniestros', siniestros, name='siniestros'),
    path('recomendados/', recomendados, name='recomendados'),
    path('misseguros', misseguros, name='misseguros'),
    path('solicitar_baja', solicitar_baja, name='solicitar_baja'),
    path('solicitar_baja_auto', solicitar_baja_auto, name='solicitar_baja_auto'),
    path('solicitud_renovacion_auto', solicitud_renovacion_auto, name='solicitud_renovacion_auto'),
    path('contactanos/', contactanos, name='contactanos'),
    path('get_data/', get_data, name='get_data'),
    path('get_modelos/', get_modelos, name='get_modelos'),
    path('get_annos/', get_annos, name='get_annos'),
    path('cotizacion_manual/', cotizacion_manual, name='cotizacion_manual'),
    path('guardar_poliza/', guardar_poliza, name='guardar_poliza'),
    path('generar_cotizacion/', generar_cotizacion, name='generar_cotizacion'),
    path('calcular_tabla_pagos/', calcular_tabla_pagos_polizas, name='calcular_tabla_pagos'),
    path('print_recibo/', print_recibo, name='print_recibo'),
    path('print_cotizacion/', print_cotizacion, name='print_cotizacion'),
    path('print_documentos/', print_documentos, name='print_documentos'),
    path('print_condiciones/', print_condiciones, name='print_condiciones'),
    path('print_orden_trabajo/', print_orden_trabajo, name='print_orden_trabajo'),
    path('print_orden_trabajo_sepelio/', print_orden_trabajo_sepelio, name='print_orden_trabajo_sepelio'),
    path('print_orden_trabajo_accidente/', print_orden_trabajo_accidente, name='print_orden_trabajo_accidente'),
    path('print_cesion/', print_cesion, name='print_cesion'),
    path('print_soa/', print_soa, name='print_soa'),
    path('enviar_contacto/', enviar_contacto, name='enviar_contacto'),
    path('admin_tasks/', admin_tasks, name='admin_tasks'),


    path('guardar_sepelio/', guardar_sepelio, name='guardar_sepelio'),
    path('costo_accidente/', costo_accidente, name='costo_accidente'),
    path('guardar_accidente/', guardar_accidente, name='guardar_accidente'),
    path('restablecer_password/', restablecer_password, name='restablecer_password'),
    path('invitacion/', invitacion, name='invitacion'),

    path('download/', download, name="download"),
    path('login/', LoginView.as_view(template_name='cotizador/login.html'), name="login"),
    path('logout/', LogoutView.as_view(next_page="/"), name="logout"),

    path('ingresar_numero_poliza', ingresar_numero_poliza, name="ingresar_numero_poliza"),
    path('javascript/<file>/', javascript, name="javascript"),
]

frontend/apps/trustseguros/urls.py
from django.urls import path
from .views import *

app_name = "trustseguros"

urlpatterns = [
    path('', index, name="index"),
    path('profile/', profile, name="profile"),
    path('persona_natural/', PersonaNatural.as_view(), name="persona_natural"),
    path('persona_juridica/', PersonaJuridica.as_view(), name="persona_juridica"),
    path('lineas/', Lineas.as_view(), name="lineas"),
    path('campains/', Campains.as_view(), name="campains"),
    path('tipo_doc/', TiposDocumentos.as_view(), name="tipo_doc"),
    path('aseguradoras/', Aseguradoras.as_view(), name="aseguradoras"),
    path('tarifas/', Tarifas.as_view(), name="tarifas"),
    path('grupos/', Grupos.as_view(), name="grupos"),
    path('ramos/', Ramos.as_view(), name="ramos"),
    path('subramos/', SubRamos.as_view(), name="subramos"),
    path('seguimientos/', Seguimientos.as_view(), name="seguimientos"),
    path('polizas/', Polizas.as_view(), name="polizas"),
    path('tramites/', Tramites.as_view(), name="tramites"),
    path('configcotizador/', ConfiguracionCotizador.as_view(), name="configcotizador"),
    path('cargaoportunidades/', CargaOportunidades.as_view(), name="cargaoportunidades"),
    path('usuarios/', Usuarios.as_view(), name="usuarios"),
    path('oportunidades/<int:linea>/', Oportunidades.as_view(), name="oportunidades"),
    path('roles/', Roles.as_view(), name="roles"),
    path('documentos/', documentos, name="documentos"),
    path('comentarios/', comentarios, name="comentarios"),
    path('cobranza/', Recibos.as_view(), name="recibos"),
    path('siniestrotramite/', SiniestroTramite.as_view(), name="siniestrotramite"),
    path('siniestro/', Siniestros.as_view(), name="siniestro"),
    path('travel_currencies/', CurrencyTravelView.as_view(), name="travel_currencies"),
    path('travel_categories/', PlanCategoryTravelView.as_view(), name="travel_categories"),
    path('travel_territories/', TerritoryTravelView.as_view(), name="travel_territories"),
    path('travel_countries/', CountryTravelView.as_view(), name="travel_countries"),
    path('travel_cities/', CityTravelView.as_view(), name="travel_cities"),
    path('travel_plans/', PlanTravelView.as_view(), name="travel_plans"),
    path('travel_asistencias/', AsistenciaTravelView.as_view(), name="travel_asistencias"),



    path('reporte_tramite/', ReporteTramite.as_view(), name="reporte_tramite"),
    path('reporte_poliza_emitida/', ReportePolizaEmitida.as_view(), name="reporte_poliza_emitida"),
    path('reporte_poliza_cancelada/', ReportePolizaCancelada.as_view(), name="reporte_poliza_cancelada"),
    path('reporte_poliza_renovada/', ReportePolizaRenovada.as_view(), name="reporte_poliza_renovada"),
    path('reporte_poliza_vencer/', ReportePolizaPorVencer.as_view(), name="reporte_poliza_vencer"),
    path('reporte_crm/', ReporteCRM.as_view(), name="reporte_crm"),
    path('reporte_cotizaciones/', ReporteCotizaciones.as_view(), name="reporte_cotizaciones"),
    path('reporte_siniestro/', ReporteSiniestro.as_view(), name="reporte_siniestro"),
    path('reporte_mora/', ReporteMora.as_view(), name="reporte_mora"),
    path('reporte_comision/', ReporteComision.as_view(), name="reporte_comision"),
]

webtrust/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('backend/', include('backend.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/ajax/', include('grappelli_extras.ajax_urls')),
    path('cotizador/', include('frontend.apps.cotizador.urls')),
    path('trustseguros/', include('frontend.apps.trustseguros.urls')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/apps/cotizador/forms.py
from backend.models import Recomendado
from django import forms
from django.core.validators import RegexValidator


class RecomendadoForm(forms.ModelForm):
    primer_nombre = forms.CharField(max_length=125)
    apellido_paterno = forms.CharField(max_length=125)
    celular = forms.CharField(max_length=8, validators=[RegexValidator('[0-9]{8,8}'), ])

    class Meta:
        model = Recomendado
        fields = '__all__'

frontend/apps/cotizador/views.py
from django.shortcuts import render, HttpResponse, render_to_response, Http404, HttpResponseRedirect
from django.http.response import JsonResponse
from backend.signals import *
from backend.utils import calcular_tabla_cuotas
from grappelli_extras.utils import Codec
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from backend.forms import *
from django.template.loader import render_to_string
from easy_pdf.rendering import render_to_pdf_response, render_to_pdf
from datetime import datetime
from django.db.models import Count, Avg
from utils.utils import send_email
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password
from django.conf import settings
import os
from django.db.models import Sum
from backend.decorators import profile_required
import random
import string
from openpyxl import Workbook
from openpyxl.styles import Border, Side, Alignment, Font
from django.contrib.auth import update_session_auth_hash
import secrets
from django.template import Template, Context
from django.contrib import messages
from .forms import RecomendadoForm
from utils.utils import send_email


# region views cotizador

@profile_required
@login_required(login_url="/cotizador/login/")
def inicio(request):
    context = {
        'config': get_config(request.user)
    }
    if request.method == "POST":
        form = ProfileForm(request.POST)
        context['perfil_form'] = form
        if form.is_valid():
            data = form.cleaned_data
            user = request.user
            user.first_name = data['first_name']
            user.last_name = data['last_name']
            user.email = data['email']
            user.save()
    return render(request, 'cotizador/base.html', context=context)


def _prepare_marca(marca):
    return (marca['marca'], marca['marca'])


def _prepare_modelo(modelo):
    return (modelo['modelo'], modelo['modelo'])


def _prepare_annos(anno):
    return (anno['anno'], anno['anno'])


@profile_required
@login_required(login_url="/cotizador/login/")
def cotizar(request):
    config = get_config(request.user)
    soa_descontado = round((config.soa_automovil * (1 - config.soa_descuento)), 2)
    today = datetime.now()
    year = int(str(today.year))
    marcas = Referencia.objects.values('marca').annotate(annos=Count('anno')).order_by('marca')
    annos = Referencia.objects.filter(marca=marcas[0]['marca']).values('anno').annotate(
        Count('valor')).order_by('marca', 'anno')
    modelos = Referencia.objects.filter(marca=marcas[0]['marca'], anno=annos[0]['anno']).values('modelo').annotate(
        Count('valor')).order_by('marca', 'anno', 'modelo')
    # annos = range(year - 10, year + 2)
    annos = [_prepare_annos(a) for a in annos]
    marcas = [_prepare_marca(marca) for marca in marcas]
    modelos = [_prepare_modelo(modelo) for modelo in modelos]
    context = {
        'marcas': marcas, 'modelos': modelos, 'annos': annos,
        'aseguradoras': Aseguradora.objects.filter(active=True),
        'anno_actual': year, 'soa_descontado': soa_descontado,
        'config': config
    }
    return render(request, 'cotizador/cotizar.html', context)


def cotizacion_manual(request):
    nombres = request.user.first_name
    apellidos = request.user.last_name
    telefono = ""
    email = request.user.email
    marca = request.POST.get('marca')
    modelo = request.POST.get('modelo')
    anno = request.POST.get('anno')
    chasis = request.POST.get('chasis')
    motor = request.POST.get('motor')
    color = request.POST.get('color')
    placa = request.POST.get('placa')
    uso = request.POST.get('uso')
    html = render_to_string('cotizador/email/notificacion.html', {
        'nombres': nombres, 'apellidos': apellidos, 'telefono': telefono,
        'email': email, 'marca': marca, 'modelo': modelo, 'anno': anno,
        'chasis': chasis, 'motor': motor, 'color': color, 'placa': placa,
        'uso': uso
    })
    circulacion = request.FILES['file_circulacion']
    files = [("attachment", (circulacion.name, circulacion)), ]
    receipt = "cesarabel@deltacopiers.com,ventas@trustcorreduria.com,gcarrion@trustcorreduria.com"
    subject = "Se ha recibido una solicitud de cotización manual"
    send_email(subject=subject, receipt=receipt, html=html, files=files)
    ticket = Tramite()
    ticket.user = request.user
    ticket.descripcion = "COTIZACIÓN DE SEGURO DE AUTOMOVIL"
    ticket.marca = marca
    ticket.modelo = modelo
    ticket.anno = anno
    ticket.chasis = chasis
    ticket.motor = motor
    ticket.circulacion = circulacion
    ticket.placa = placa
    ticket.color = color
    ticket.save()
    return JsonResponse({})


@csrf_exempt
def get_annos(request):
    marca = request.POST.get('marca')
    annos = Referencia.objects.filter(marca=marca).values(
        'anno').annotate(models.Count('valor')).order_by('anno')
    data = [x['anno'] for x in annos]
    return JsonResponse(data, safe=False)


@csrf_exempt
def get_modelos(request):
    marca = request.POST.get('marca')
    anno = request.POST.get('anno')
    modelos = Referencia.objects.filter(marca=marca, anno=anno).values(
        'modelo').annotate(models.Count('valor')).order_by('modelo')
    data = [x['modelo'] for x in modelos]
    return JsonResponse(data, safe=False)


# @csrf_exempt
# def calcular_coberturas(coberturas, valor_nuevo, anno):
#     data = []
#     for c in coberturas:
#         for a in Aseguradora.objects.filter(active=True):
#             obj = {}
#             obj['cobertura'] = c.id
#             obj['aseguradora'] = a.id
#             p = c.get_precio(aseguradora=a)
#             if p.available:
#                 if c.tipo_exceso == '0.0':
#                     obj['valor'] = 0.0
#                 if c.tipo_exceso == 'valor_nuevo':
#                     obj['valor'] = calcular_exceso(valor_nuevo, c.tipo_calculo, p.valor)
#                 if c.tipo_exceso == 'valor_depreciado':
#                     valor_depreciado = a.depreciar(valor_nuevo, anno, 1)
#                     obj['valor'] = calcular_exceso(valor_depreciado, c.tipo_calculo, p.valor)
#                 data.append(obj)
#     return data


def el_mas_probable(referencias):
    average = referencias.aggregate(Avg('valor'))['valor__avg']
    elegido = referencias[0]
    diff = abs(elegido.valor - average)
    for r in referencias:
        ndiff = abs(r.valor - average)
        if ndiff < diff:
            diff = ndiff
            elegido = r
    return elegido


def anno_mas_cercano(years, year):
    diff = None
    selected = None
    for y in years:
        _diff = abs(int(y) - int(year))
        if diff:
            if _diff < diff:
                selected = y
                diff = _diff
        else:
            diff = _diff
            selected = y
    return selected


@csrf_exempt
def get_data(request):
    config = get_config(request.user)
    marca = request.POST.get('marca')
    porcentaje_deducible = config.porcentaje_deducible
    porcentaje_deducible_extension = config.porcentaje_deducible_extencion_territorial
    minimo_deducible = config.minimo_deducible
    minimo_deducible_extension = config.minimo_deducible
    porcentaje = str(round(config.porcentaje_deducible * 100, 0)).replace('.0', '%')
    porcentaje_extension = str(round(config.porcentaje_deducible_extencion_territorial * 100, 0)).replace('.0', '%')
    if marca in Marca.objects.all().values_list('marca', flat=True):
        marca_recargo = Marca.objects.get(marca=marca)
        minimo_deducible = marca_recargo.minimo
        porcentaje_deducible = marca_recargo.porcentaje_deducible
        porcentaje_deducible_extension = marca_recargo.porcentaje_deducible
        minimo_deducible_extension = marca_recargo.minimo
        porcentaje = marca_recargo.porcentaje()
        porcentaje_extension = marca_recargo.porcentaje()
        deducible_rotura_vidrios = marca_recargo.rotura_vidrios or 0.0
    else:
        deducible_rotura_vidrios = 0.0
    modelo = request.POST.get('modelo')
    anno = request.POST.get('anno')
    chasis = request.POST.get('chasis', None)
    exceso = float(request.POST.get('exceso'))
    chasis_encontrado = False

    try:
        if chasis and chasis != '':
            valor_nuevo = Referencia.objects.get(chasis=chasis)
            chasis_encontrado = True
        else:
            raise Exception()
    except:
        referencias = Referencia.objects.filter(marca=marca, modelo=modelo, anno=anno)
        if referencias.count() > 0:
            valor_nuevo = el_mas_probable(referencias)
        else:
            referencias = Referencia.objects.filter(marca=marca, modelo=modelo, anno__lt=anno).order_by('-anno')
            if referencias.count() > 0:
                _year = referencias[0].anno
                referencias = referencias.filter(anno=_year)
                valor_nuevo = el_mas_probable(referencias).to_json()
            else:
                referencias = Referencia.objects.filter(marca=marca, modelo=modelo).order_by('-anno')
                if referencias.count() > 0:
                    years = [x.anno for x in referencias.distinct('anno')]
                    _year = anno_mas_cercano(years, anno)
                    referencias = referencias.filter(anno=_year)
                    valor_nuevo = el_mas_probable(referencias).to_json()
                else:
                    valor_nuevo = {'marca': marca, 'modelo': modelo, 'anno': anno, 'valor': 0.0}

    aseguradora = config.aseguradora_automovil
    prima = round((valor_nuevo['valor'] * config.tasa_automovil) / 1000, 2)
    exceso = round((exceso / 2500) * 50, 2)
    vidrios = round((valor_nuevo['valor'] * 5) / 100, 2)
    prima_total = prima + config.soa_automovil + exceso
    emision = round(((prima + exceso) * aseguradora.emision) / 100, 2)
    iva = round(((prima + exceso + emision) * 15) / 100, 2)
    total = round(prima_total + emision + iva, 2)

frontend/templates/trustseguros/lte/perfilusuario-form.html
{% extends 'adminlte/datatables-modal.html' %}


{% block buttons %}
    {% if instance.id %}
        <button type="button" class="btn btn-warning" id="btn-cambiar-pass"
                data-id="{{ instance.id }}">
            <i class="fa fa-lock"></i>
            Cambiar password
        </button>
    {% endif %}
    {{ block.super }}
{% endblock %}

frontend/templates/trustseguros/lte/recibo-datatables.html
{% extends 'adminlte/datatables.html' %}
{% load static datatables %}


{% block style %}
    {{ block.super }}
    <style type="text/css">
        select[name="pagocuota-medio_pago"] {
            min-width: 185px;
        }
    </style>
{% endblock %}


{% block javascript %}

    {{ block.super }}
    <script type="text/javascript">

        function imprimir_estado_cuenta(response, textStatus, xhr) {
            let blob = new Blob([response], {type: 'application/pdf'});
            let link = document.createElement('a');
            link.href = window.URL.createObjectURL(blob);
            link.download = `Estado de cuenta.pdf`;
            link.click();
            $('.btn-perform').removeAttr('disabled')
        }

        $(document).ready(function () {

            $('.dt-buttons').css({
                display: 'none'
            });

            $(document).on('change', '#id_recibos', function () {
                $('#id_recibo_editar').val($(this).val());
                const form = $('#{{ opts.model_name }}-form')[0];
                perform_action(form, 'cambiar_recibo', process_response);
            });

            const calcular_prima_neta = function () {
                let prima = parseFloat($('input[name="subtotal"]').val());
                let descuento = parseFloat($('input[name="descuento"]').val());
                $('input[name="prima_neta"]').val((prima - descuento).toFixed(2))
                    .trigger('change')
            };

            const calcular_total = function () {
                let prima_neta = parseFloat($('input[name="prima_neta"]').val());
                let emision = parseFloat($('input[name="emision"]').val());
                let iva = parseFloat($('input[name="iva"]').val());
                let otros = parseFloat($('input[name="otros"]').val());
                $('input[name="total"]').val((prima_neta + emision + iva + otros).toFixed(2)).trigger('change')
            };

            const calcular_comision = function () {
                let prima_neta = parseFloat($('input[name="prima_neta"]').val());
                let per_comision = parseFloat($('input[name="per_comision"]').val());
                $('input[name="amount_comision"]').val(((prima_neta * per_comision) / 100).toFixed(2))
            };

            const calcular_tabla_pagos = function () {
                const form = $('#poliza-form')[0];
                const data = new FormData(form);
                data.append('calcular_tabla_pagos', 'calcular_tabla_pagos');
                $.ajax(".", {
                    method: "POST",
                    data: data,
                    processData: false,
                    contentType: false,
                    success: function (response) {
                        const pagos = $('#id_tabla_pagos tbody').empty();
                        $.each(response, function (i, o) {
                            pagos.append(`
                                    <tr>
                                        <td>
                                            <input type="hidden" name="tabla_pagos_id">
                                            <input type="text" name="tabla_pagos_numero" class="form-control" readonly value="${o.numero}" style="text-align: center">
                                        </td>
                                        <td>
                                            <input type="text" name="tabla_pagos_fecha_vence" class="form-control" readonly value="${o.fecha}" style="text-align: center">
                                        </td>
                                        <td>
                                            <input type="text" name="tabla_pagos_monto" class="form-control numberinput" value="${o.monto}">
                                        </td>
                                        <td>
                                            <input type="text" name="tabla_pagos_saldo" class="form-control numberinput" value="${o.monto}">
                                        </td>
                                        <td>
                                            <input type="text" name="tabla_pagos_monto_comision" class="form-control numberinput" value="${o.monto_comision}">
                                        </td>
                                        <td>
                                            <input type="text" name="tabla_pagos_estado" class="form-control" readonly value="${o.estado}">
                                        </td>
                                        <td>
                                            <input type="text" name="tabla_pagos_mora" class="form-control" readonly value="${o.mora}" style="text-align: center">
                                        </td>
                                    </tr>

                            `)
                        });
                        let total_pagos = 0.0;
                        $.each($('input[name="tabla_pagos_monto"]'), function (i, o) {
                            total_pagos += parseFloat($(o).val())
                        });
                        $('#id_total_pagos').val(total_pagos);
                    }
                })
            };

            $(document).on('change', 'input[name="tabla_pagos_monto"]', function () {
                let total_pagos = 0.0;
                $.each($('input[name="tabla_pagos_monto"]'), function (i, o) {
                    total_pagos += parseFloat($(o).val())
                });
                $('#id_total_pagos').val(total_pagos);
            });

            $(document).on('change', 'input[name="subtotal"]', calcular_prima_neta);
            $(document).on('change', 'input[name="descuento"]', calcular_prima_neta);

            $(document).on('change', 'input[name="prima_neta"]', calcular_total);
            $(document).on('change', 'input[name="emision"]', calcular_total);
            $(document).on('change', 'input[name="iva"]', calcular_total);
            $(document).on('change', 'input[name="otros"]', calcular_total);

            $(document).on('change', 'input[name="prima_neta"]', calcular_comision);

            $(document).on('change', '#id_cantidad_cuotas', calcular_tabla_pagos);
            $(document).on('change', '#id_fecha_pago', calcular_tabla_pagos);
            $(document).on('change', 'input[name="total"]', calcular_tabla_pagos);
            $(document).on('change', 'input[name="per_comision"]', function () {
                const percent = parseFloat($(this).val());
                $.each($('input[name="tabla_pagos_monto"]'), function (i, o) {
                    const monto = parseFloat($(o).val().replace(',', ''));
                    const comision = (monto * percent) / 100
                    $('input[name="tabla_pagos_monto_comision"]').val(comision.toFixed(2));
                });
                calcular_comision();
            });

            $(document).on('change', '#id_f_pago', function () {
                if ($(this).val() === "1") {
                    $('#id_cuotas').attr('readonly', 'readonly').val('1').trigger('change')
                } else {
                    $('#id_cuotas').removeAttr('readonly')
                }
            });
            $(document).on('click', '#btn-ecuenta', function () {
                const _this = $(this);
                $.ajax('.', {
                    method: "POST",
                    data: {
                        pk: $('input[name="pk"]').val(),
                        estado_cuenta: 'estado_cuenta'
                    },
                    success: function (response) {
                        let blob = new Blob([response], {type: 'application/pdf'});
                        let link = document.createElement('a');
                        link.href = window.URL.createObjectURL(blob);
                        link.download = "Estado de cuenta.pdf";
                        link.click();
                        _this.removeAttr('disabled')
                    }
                })
            });
            $(document).on('click', '#btn-null', function () {
                swal({
                    title: 'Estas seguro?',
                    text: "Esta acción no se puede revertir!",
                    imageUrl: "{% static 'cotizador/images/trusty/pregunta.png' %}",
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Si, anúlalo!',
                    cancelButtonText: 'Cancelar'
                }).then((result) => {
                    if (result.value) {
                        swal(
                            'Recibo anulado con éxito!',
                            'Todas las operaciones relacionadas se realizaron correctamente.',
                            'success'
                        ).then(() => {
                            const form = $('#{{ opts.model_name }}-form');
                            const data = new FormData(form[0]);
                            perform_action(data, 'POST', '.', 'anular_recibo')
                        })
                    }
                })

            });

            $(document).on('click', '.btn-edit-cuota', function () {
                const _this = $(this);
                $.ajax('.', {
                    method: "POST",
                    data: {
                        cuota: _this.data('cuota'),
                        opencuota: 'opencuota'
                    },
                    success: function (response) {
                        modal.iziModal('destroy');
                        modal.empty().append(response.form);
                        modal.iziModal({
                            zindex: 1500, width: 1300,
                            title: response.instance.str,
                            subtitle: 'datos de la cuota',
                            headerColor: "#326634", padding: 20,
                            onClosed: () => {
                                open_object(response.instance.poliza.id)
                            }
                        });
                        modal.iziModal('open');
                    }
                });
            });

            $(document).on('click', '.btn-add-cuota', function () {
                $.ajax('.', {
                    method: "POST",
                    data: {
                        nuevopago: 'nuevopago'
                    },
                    success: function (response) {
                        const pagos = $('#id_pagos tbody');
                        pagos.append(response.html)
                    }
                })
            });

            $(document).on('click', '.btn-save-cuota', function () {
                const cuotaform = document.getElementById('cuota-form');
                const data = new FormData(cuotaform);
                data.append('guardarcuota', 'guardarcuota');
                $.ajax('.', {
                    method: "POST",
                    data: data,
                    processData: false,
                    contentType: false,
                    success: function (response) {
                        redraw_object(response)
                    }
                })
            });

            $(document).on('click', '.btn-del-pago', function () {
                const _this = $(this);
                const tr = _this.parents('tr');
                if (_this.data('id')) {
                    $.ajax($ajax_execute, {
                        method: "POST",
                        data: {
                            app_label: 'backend', model: 'pagocuota', id: _this.data('id'),
                            'view': 'delete'
                        },
                        success: function (response) {
                            tr.remove();
                        }
                    })
                } else {
                    tr.remove()
                }
            });

            $(document).on('click', '#bitacorabtn-add-comment', function () {
                let comment = $('#bitacora-comentario-input').val();
                if (comment.length > 0) {
                    $.ajax("{% url 'trustseguros:comentarios' %}", {
                        method: "post",
                        data: {
                            new: 'new', comentario: comment,
                            app_label: 'backend', model: 'poliza',
                            pk: $('input[name="pk"]').val()
                        },
                        success: function (response) {
                            $('#bitacora-table').prepend(`
                                <tr>
                                    <td colspan="2">${response.instance.comentario}</td>
                                    <td>${response.instance.created_user.username}</td>
                                    <td>${response.instance.created}</td>
                                </tr>
                            `);
                            $('#bitacora-comentario-input').val('')
                        }
                    })
                }
            });

        });

    </script>
{% endblock %}